### ISSUE TITLE
not working wiht magento 2.4.1

### ISSUE THREAD

**Issue by ia-gaurav** [tuyennn/magento2-outofstockatlast#1]
Magento Version -2.4.1

Steps - Intalled moduled, deployed , indexing done still not working

**Comment by tuyennn** [comment]
I have 2 products set as Out of Stock
For all dir DESC or ASC - all Filters: 
Still find it works properly 
![Selection_044](https://user-images.githubusercontent.com/4010395/118621601-b9130e80-b7f0-11eb-9194-4f25960b99d2.jpg)
![Selection_045](https://user-images.githubusercontent.com/4010395/118621612-ba443b80-b7f0-11eb-8e31-be9879fb6045.jpg)
![Selection_046](https://user-images.githubusercontent.com/4010395/118621615-badcd200-b7f0-11eb-9dd9-8e9ddc4a3a6c.jpg)
![Selection_047](https://user-images.githubusercontent.com/4010395/118621619-bb756880-b7f0-11eb-8a7d-235f78ede47d.jpg)
![Selection_048](https://user-images.githubusercontent.com/4010395/118621622-bc0dff00-b7f0-11eb-92fc-3044b00dfaa4.jpg)
![Selection_049](https://user-images.githubusercontent.com/4010395/118621625-bc0dff00-b7f0-11eb-879d-628f1d6ef2bd.jpg)

**Comment by ia-gaurav** [comment]
i see below error in log :

Uncaught TypeError: Return value of GhoSter\OutOfStockAtLast\Model\ResourceModel\Inventory::getStockStatus() must be of the type int, bool returned in /app/code/GhoSter/OutOfStockAtLast/Model/ResourceModel/Inventory.php:79

**Comment by ia-gaurav** [comment]
i noticed that module is not working when Smile Elastic Suite ( https://github.com/Smile-SA/elasticsuite ) is enabled .

Can you check which part is doing conflict

**Comment by tuyennn** [comment]
@ia-gaurav should be improvement compatibility for next release. Will close this issue

**Comment by tuyennn** [comment]
@ia-gaurav now the module is compatibility with Smile Elastic Suite
