### ISSUE TITLE
installed in Magento 2.4.2  no working

### ISSUE THREAD

**Issue by kevin0320** [tuyennn/magento2-outofstockatlast#13]
installed in Magento 2.4.2 , nothing change. module not working. Please advise. thanks

**Comment by tuyennn** [comment]
Refer to [README.md](https://github.com/tuyennn/magento2-outofstockatlast/blob/master/README.md) for instruction

**Comment by kevin0320** [comment]
I did follow your instructions but no surprise for me.

**Comment by kevin0320** [comment]
It’s working.  I think might be due to the cache issue.  By the way, is it working with configurable product.  Thanks

**Comment by kevin0320** [comment]
Tested. Working perfect. Thanks!

**Comment by steffen-wirth** [comment]
Hi @tuyennn,
i had to delete the whole elasticsearch index before it worked, is this normal?

**Comment by steffen-wirth** [comment]
@tuyennn the cli reindex wasn't working in the beginning, i had to cleanup ES with curl -X DELETE 'http://localhost:PORT/magento2_*' and after reindex it started to work - thanks for the module - 'll spend a beer
