### ISSUE TITLE
Sort by Position of products not working on category page

### ISSUE THREAD

**Issue by PiroozMB** [tuyennn/magento2-outofstockatlast#22]
after installing the extension , sorting products by position are not working anymore on category pages. 
I got this once working in magento 2.2.3 in ListProduct.php using this code:
$collection->addExpressionAttributeToSelect('in_stock', 'IFNULL(stock_status_index.stock_status,0)', array());
$collection->getSelect()->reset('order');
$collection->getSelect()->order('in_stock DESC');

**Comment by tuyennn** [comment]
@PiroozMB I'm not sure with your issue but could you update the issue follow the issue template which is your Preconditions such as:
Magento version? elastic search version

**Comment by PiroozMB** [comment]
Hi. I installed magento2.4.3 and elasticsearch 8.

**Comment by PiroozMB** [comment]
Sorry, I came to understanding that the issue was with magent version 2.4.3 itself not with your extension. I solved it. You can close this. Thnx.
