### ISSUE TITLE
Compatibility with smile/elasticsuite

### ISSUE THREAD

**Issue by tuyennn** [tuyennn/magento2-outofstockatlast#3]
### Preconditions (*)
1. Request from issue https://github.com/tuyennn/magento2-outofstockatlast/issues/1

### Steps to reproduce (*)
1. None

### Expected result (*)
1. Compatibility with smile/elasticsuite

**Comment by vivekcoder007** [comment]
I am facing issue with making it work with elasticsearch - when mannual sort is enabled

Steps 
1: Edit category
2: Mannual sort and add out of stock products - https://raw.githubusercontent.com/Smile-SA/elasticsuite/2.10.x/doc/static/term-merchandiser.gif
3: for products not added via mannual sort it works fine, but not if out of stock products are set in mannual sort it does not moves them in last

**Comment by ia-Gaury** [comment]
@vivekcoder007 @tuyennn  - did u got any solution to above

**Comment by tuyennn** [comment]
Thanks @vivekcoder007 @ia-Gaury the manual sorting Smile-SA was compatible with version [v1.0.4](https://github.com/tuyennn/magento2-outofstockatlast/releases/tag/v1.0.4)
https://github.com/tuyennn/magento2-outofstockatlast/pull/21
