### ISSUE TITLE
[FEATURE] - Other Search Engines

### ISSUE THREAD

**Issue by kestraly** [tuyennn/magento2-outofstockatlast#30]
Hi, 

This is fantastic work. I'm just looking at integrating it with a few other areas such as Amasty ElasticSearch and Mirasvit Search Ultimate.

Neither paid plugin gives the option to move out of stock last.

Any experience with either? Just looking to update the di.xml files for both to allow for your out_of_stock flag

**Comment by tuyennn** [comment]
@kestraly not sure you're mentioning to Sphinx or extended Elasticsearch 7 on Mirasvit Search Ultimate?
