### ISSUE TITLE
Still not working with Adobe Commerce ver. 2.4.6 & ElasticSuite Open Source ver. 2.11.2

### ISSUE THREAD

**Issue by dnkalavadia** [tuyennn/magento2-outofstockatlast#38]
### Preconditions (*)
1. Adobe Commerce ver. 2.4.6 & ElasticSuite Open Source ver. 2.11.2

### Expected result (*)
![screenshot-www drummondgolf com au-2023 06 30-11_04_19](https://github.com/tuyennn/magento2-outofstockatlast/assets/7344785/507b603f-fab1-4a9f-926d-7244896d301c)

### Actual result (*)
![screenshot-integration2-hohc4oi-i6nuu45zi4c4c ap-3 magentosite cloud-2023 06 30-11_06_38](https://github.com/tuyennn/magento2-outofstockatlast/assets/7344785/d38e9937-724a-41d2-8b1b-d2915d9623ca)

**Comment by tuyennn** [comment]
@dnkalavadia we cannot reproduce your bug on magento 2.4.6-p1
![image](https://github.com/tuyennn/magento2-outofstockatlast/assets/4010395/262cf0b3-29f0-4eae-9c07-6ae2f1db4670)
![image](https://github.com/tuyennn/magento2-outofstockatlast/assets/4010395/9205e742-de4c-4cc6-a5f1-c695d9231a2c)



Kindly follow the instruction on
https://github.com/tuyennn/magento2-outofstockatlast/blob/master/README.md

**Comment by dnkalavadia** [comment]
Working fine with other environment and database 
Thanks
