### ISSUE TITLE
order of Widget new products is broken

### ISSUE THREAD

**Issue by ppeyman** [tuyennn/magento2-outofstockatlast#50]
module

Preconditions 
-------------
I installed it on magento 2.4.6-p3 with elasticsearch version 7.17.7.

reproduce 
---------------------
Everything Works Well But when i add a new Products Widget to Home page or etc sort of new Products Broken and show  old or random products

Expected Result 
-----------------------------------
![image](https://github.com/tuyennn/magento2-outofstockatlast/assets/13271466/5029f13e-43fb-4627-905a-4d6393e4e26c)

Actual result
-----------------------------
![image](https://github.com/tuyennn/magento2-outofstockatlast/assets/13271466/9202403b-9b4f-4ff4-87dc-dff9f50ab6df)

as you see old products show after enable this module

Thank you !

**Comment by tuyennn** [comment]
Thanks @ppeyman for the report, as I know the new products widget used **news_from_date** as default sorting instead custom sorting **out of stock** attribute.
Please see below for reference
https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Catalog/Block/Product/Widget/NewWidget.php#L86-L118
https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Catalog/Block/Product/NewProduct.php#L147-L150

Further more we support the Product List only, there was no plans for widget yet.

**Comment by ppeyman** [comment]
> Thanks @ppeyman for the report, as I know the new products widget used **news_from_date** as default sorting instead custom sorting **out of stock** attribute. Please see below for reference https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Catalog/Block/Product/Widget/NewWidget.php#L86-L118 https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Catalog/Block/Product/NewProduct.php#L147-L150
> 
> Further more we support the Product List only, there was no plans for widget yet.

so that mean i disable new products in our site ?

**Comment by tuyennn** [comment]
@ppeyman not sure, but for sure our module took no effect to the New Products widget and the widget works as Out of the box Magento

**Comment by tuyennn** [comment]
Here what I archived before and after enabling/disabling module, reindexing
**Before**
![Selection_157](https://github.com/tuyennn/magento2-outofstockatlast/assets/4010395/102fee26-a37f-4baa-b4cc-f18b5e3a98b1)

**After**
![Selection_158](https://github.com/tuyennn/magento2-outofstockatlast/assets/4010395/2f169782-3b2c-4a17-bbd8-9cf5b9be7726)


See https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Catalog/Block/Product/Widget/NewWidget.php#L86-L118

I supposed the logic as your screenshot came to Magento/Catalog/Block/Product/Widget/NewWidget.php::_getRecentlyAddedProductsCollection
Where the order was sorting by **created_at** **desc**

Are you able to double check the logic?

**Comment by ppeyman** [comment]
my logic : 

```
  protected function _getProductCollection()
    {
        switch ($this->getDisplayType()) {
            case self::DISPLAY_TYPE_NEW_PRODUCTS:
                $collection = parent::_getProductCollection()
                    ->setPageSize($this->getPageSize())
                    ->setCurPage($this->getCurrentPage());
                break;
            default:
                $collection = $this->_getRecentlyAddedProductsCollection();
                break;
        }
        return $collection;
    }

    /**
     * Prepare collection for recent product list
     *
     * @return \Magento\Catalog\Model\ResourceModel\Product\Collection|Object|\Magento\Framework\Data\Collection
     */
    protected function _getRecentlyAddedProductsCollection()
    {
        /** @var $collection \Magento\Catalog\Model\ResourceModel\Product\Collection */
        $collection = $this->_productCollectionFactory->create();
        $collection->setVisibility($this->_catalogProductVisibility->getVisibleInCatalogIds());

        $collection = $this->_addProductAttributesAndPrices($collection)
            ->addStoreFilter()
            ->addAttributeToSort('created_at', 'desc')
            ->setPageSize($this->getPageSize())
            ->setCurPage($this->getCurrentPage());
        return $collection;
    }
```

**Comment by ppeyman** [comment]
> 

Hi dear i test it on new fresh magento installation and add four old products and add four new products 
when your module is enabled doesn`t show new products and showing another products 
please check it like me and see results 

in adminpanel shows well and true : 

![image](https://github.com/tuyennn/magento2-outofstockatlast/assets/13271466/733d9db7-df34-4430-af78-f82c4d6715a7)

in frontend show false : 

![image](https://github.com/tuyennn/magento2-outofstockatlast/assets/13271466/a25aea74-86ca-4a11-8275-e9746da133ec)


thank you
