### ISSUE TITLE
The module does not activate

### ISSUE THREAD

**Issue by poozhan** [tuyennn/magento2-outofstockatlast#51]
### Preconditions (*)

1.I installed the module with Composer
The module is located in the vendor folder
But after running the activation command, the following error appears

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. 
2.

### Actual result (*)

1. GhoSter_OutOfStockAtLast : Module does not exist

2.

**Comment by tuyennn** [comment]
Refer to instruction README.md

**Comment by poozhan** [comment]
Don't you understand what I mean?
I installed with Composer and the files have gone into the vendor folder
Now, when I unzip the files in the app/code/ folder, it gives an error
I delete the files in the vendor folder, it gives me an error
It cannot be disabled either
`php bin/magento module:disable GhoSter_OutOfStockAtLast`
It is not in the list of modules

**Comment by tuyennn** [comment]
@poozhan Probably you don't know how to install a module. Have a nice day
