### ISSUE TITLE
does not work on magento v 2.4.7

### ISSUE THREAD

**Issue by gh-darvishani** [tuyennn/magento2-outofstockatlast#55]
### Preconditions (*)
Magneto version 2.4.7
php 8.2
elastic search v 7.11
single store 
 
got this error during the index :
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'inventory_stock_1' doesn't exist, query was: SELECT `inventory_stock_1`.`is_salable` FROM `inventory_stock_1` WHERE (sku = 'rugpad_free') GROUP BY `sku`

**Comment by tuyennn** [comment]
Thanks @gh-darvishani for reporting the bug, but this doesn't seem related to the module.

**Comment by tuyennn** [comment]
See this for ref https://github.com/magento/magento2/issues/19542
