### ISSUE TITLE
Hi..It is not working for configurable products.

### ISSUE THREAD

**Issue by ia-Gaury** [tuyennn/magento2-outofstockatlast#7]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by lennart-hendriksma-abovo** [comment]
Hello, i'm facing the same issue where it is not working with configurable products. any hints on what you did to make it work?
