### ISSUE TITLE
Feature Request - do not show out of stock

### ISSUE THREAD

**Issue by vivekcoder007** [tuyennn/magento2-outofstockatlast#8]
Is there way i can remove out of stock products from showing on specific category , please help me

**Comment by vivekcoder007** [comment]
i found this module very helpfule - but can you help me with below request

i want to add sidebar filter -- exclude out of stock filter so user can tick or untick it

**Comment by codewidsaurav** [comment]
yes i am also search this feature for long - @tuyennn  can you do this please - i can buy you a coffee

**Comment by tuyennn** [comment]
@codewidsaurav @vivekcoder007 this request seem to belong to Layered Navigation rather than what I want to implementation. So close this due have no effort to work on Layered Navigation
